<a href="https://colab.research.google.com/github/dizstarry/Data_Portfolio/blob/main/Manipulate_Excel_sheets_with_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import Data File into a Panda Data frame** https://archive.ics.uci.edu/ml/datasets/iris

**Data**

In [3]:
import pandas

data = pandas.read_csv('iris.data', names = ['feature0', 'feature1', 'feature2', 'feature3', 'class'])

data

     feature0  feature1  feature2  feature3           class
0         5.1       3.5       1.4       0.2     Iris-setosa
1         4.9       3.0       1.4       0.2     Iris-setosa
2         4.7       3.2       1.3       0.2     Iris-setosa
3         4.6       3.1       1.5       0.2     Iris-setosa
4         5.0       3.6       1.4       0.2     Iris-setosa
..        ...       ...       ...       ...             ...
145       6.7       3.0       5.2       2.3  Iris-virginica
146       6.3       2.5       5.0       1.9  Iris-virginica
147       6.5       3.0       5.2       2.0  Iris-virginica
148       6.2       3.4       5.4       2.3  Iris-virginica
149       5.9       3.0       5.1       1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
data = pandas.read_csv('iris.data', names = ['sepalLength', 'sepalWidth', 'petalLength', 'petalWidth', 'class'])

data

     sepalLength  sepalWidth  petalLength  petalWidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [7]:
data.to_excel('iris.xlsx', index = None)

**Excel sheet Manipulation with Python**

In [10]:
data1 = pandas.read_excel('multiple_sheets.xlsx', sheet_name ='Sheet2')

data1

,Excess Return,Systematic Risk,Total Risk,Abs. Win Rate,Rel. Win Rate,Annual Return,Excess Return.1,Systematic Risk.1,Total Risk.1,Abs. Win Rate.1,Rel. Win Rate.1,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,13,0.500,0.000,0.000,0.000,0.5,0.0,0.0256,0.0074,1.420759,0.1460,0.55,0.50,0.512,0.522,0.527,0.488,0.56,0.467
1,14,0.000,0.500,0.000,0.000,0.5,0.0,0.0460,0.0107,1.091537,0.1099,0.65,0.75,0.593,0.571,0.353,0.333,0.80,0.800
2,15,0.000,0.000,0.500,0.000,0.5,0.0,0.0417,0.0110,1.419546,0.1424,0.55,0.50,0.576,0.575,0.526,0.473,0.56,0.467
3,16,0.000,0.000,0.000,0.500,0.5,0.0,0.0357,0.0095,1.203244,0.1294,0.65,0.60,0.552,0.553,0.412,0.417,0.80,0.600
4,17,0.500,0.000,0.000,0.000,0.0,0.5,-0.0234,-0.0062,0.977325,0.1069,0.65,0.45,0.318,0.326,0.293,0.321,0.80,0.400
5,18,0.000,0.500,0.000,0.000,0.0,0.5,0.0062,0.0002,0.864122,0.0873,0.60,0.50,0.436,0.417,0.233,0.236,0.68,0.467
6,19,0.000,0.000,0.500,0.000,0.0,0.5,0.0153,0.0033,1.066938,0.1090,0.55,0.60,0.472,0.463,0.340,0.330,0.56,0.600
7,20,0.000,0.000,0.000,0.500,0.0,0.5,0.0011,-0.0006,1.007704,0.1034,0.55,0.50,0.415,0.406,0.309,0.305,0.56,0.467
8,21,0.000,0.000,0.000,0.000,0.5,0.5,0.0100,0.0007,0.800792,0.0788,0.55,0.45,0.451,0.426,0.200,0.200,0.56,0.400
9,22,0.333,0.333,0.333,0.000,0.0,0.0,0.0780,0.0213,1.509223,0.1580,0.55,0.65,0.720,0.724,0.573,0.540,0.56,0.667
10,23,0.333,0.333,0.000,0.333,0.0,0.0,0.0643,0.0161,1.347686,0.1380,0.60,0.50,0.665,0.649,0.488,0.454,0.68,0.467
11,24,0.333,0.000,0.333,0.333,0.0,0.0,0.0683,0.0202,1.674320,0.1771,0.55,0.40,0.681,0.708,0.660,0.622,0.56,0.333

In [11]:
data1 = pandas.read_excel('multiple_sheets.xlsx', sheet_name ='Sheet2', index_col = 0)

data1

,Systematic Risk,Total Risk,Abs. Win Rate,Rel. Win Rate,Annual Return,Excess Return.1,Systematic Risk.1,Total Risk.1,Abs. Win Rate.1,Rel. Win Rate.1,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
Excess Return,,,,,,,,,,,,,,,,,,
13,0.500,0.000,0.000,0.000,0.5,0.0,0.0256,0.0074,1.420759,0.1460,0.55,0.50,0.512,0.522,0.527,0.488,0.56,0.467
14,0.000,0.500,0.000,0.000,0.5,0.0,0.0460,0.0107,1.091537,0.1099,0.65,0.75,0.593,0.571,0.353,0.333,0.80,0.800
15,0.000,0.000,0.500,0.000,0.5,0.0,0.0417,0.0110,1.419546,0.1424,0.55,0.50,0.576,0.575,0.526,0.473,0.56,0.467
16,0.000,0.000,0.000,0.500,0.5,0.0,0.0357,0.0095,1.203244,0.1294,0.65,0.60,0.552,0.553,0.412,0.417,0.80,0.600
17,0.500,0.000,0.000,0.000,0.0,0.5,-0.0234,-0.0062,0.977325,0.1069,0.65,0.45,0.318,0.326,0.293,0.321,0.80,0.400
18,0.000,0.500,0.000,0.000,0.0,0.5,0.0062,0.0002,0.864122,0.0873,0.60,0.50,0.436,0.417,0.233,0.236,0.68,0.467
19,0.000,0.000,0.500,0.000,0.0,0.5,0.0153,0.0033,1.066938,0.1090,0.55,0.60,0.472,0.463,0.340,0.330,0.56,0.600
20,0.000,0.000,0.000,0.500,0.0,0.5,0.0011,-0.0006,1.007704,0.1034,0.55,0.50,0.415,0.406,0.309,0.305,0.56,0.467
21,0.000,0.000,0.000,0.000,0.5,0.5,0.0100,0.0007,0.800792,0.0788,0.55,0.45,0.451,0.426,0.200,0.200,0.56,0.400
22,0.333,0.333,0.333,0.000,0.0,0.0,0.0780,0.0213,1.509223,0.1580,0.55,0.65,0.720,0.724,0.573,0.540,0.56,0.667
23,0.333,0.333,0.000,0.333,0.0,0.0,0.0643,0.0161,1.347686,0.1380,0.60,0.50,0.665,0.649,0.488,0.454,0.68,0.467
24,0.333,0.000,0.333,0.333,0.0,0.0,0.0683,0.0202,1.674320,0.1771,0.55,0.40,0.681,0.708,0.660,0.622,0.56,0.333

In [15]:
data1 = pandas.read_excel('multiple_sheets.xlsx', sheet_name ='Sheet2', usecols= 'A,B', header = None, skiprows = 1)

data1

     0      1
0   13  0.500
1   14  0.000
2   15  0.000
3   16  0.000
4   17  0.500
5   18  0.000
6   19  0.000
7   20  0.000
8   21  0.000
9   22  0.333
10  23  0.333
11  24  0.333

In [16]:
data1 = pandas.read_excel('multiple_sheets.xlsx', sheet_name ='Sheet2',index_col= 0, header= None, skiprows= 1)

data1

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,,,,,,,,,,,,,,,,,,
13,0.500,0.000,0.000,0.000,0.5,0.0,0.0256,0.0074,1.420759,0.1460,0.55,0.50,0.512,0.522,0.527,0.488,0.56,0.467
14,0.000,0.500,0.000,0.000,0.5,0.0,0.0460,0.0107,1.091537,0.1099,0.65,0.75,0.593,0.571,0.353,0.333,0.80,0.800
15,0.000,0.000,0.500,0.000,0.5,0.0,0.0417,0.0110,1.419546,0.1424,0.55,0.50,0.576,0.575,0.526,0.473,0.56,0.467
16,0.000,0.000,0.000,0.500,0.5,0.0,0.0357,0.0095,1.203244,0.1294,0.65,0.60,0.552,0.553,0.412,0.417,0.80,0.600
17,0.500,0.000,0.000,0.000,0.0,0.5,-0.0234,-0.0062,0.977325,0.1069,0.65,0.45,0.318,0.326,0.293,0.321,0.80,0.400
18,0.000,0.500,0.000,0.000,0.0,0.5,0.0062,0.0002,0.864122,0.0873,0.60,0.50,0.436,0.417,0.233,0.236,0.68,0.467
19,0.000,0.000,0.500,0.000,0.0,0.5,0.0153,0.0033,1.066938,0.1090,0.55,0.60,0.472,0.463,0.340,0.330,0.56,0.600
20,0.000,0.000,0.000,0.500,0.0,0.5,0.0011,-0.0006,1.007704,0.1034,0.55,0.50,0.415,0.406,0.309,0.305,0.56,0.467
21,0.000,0.000,0.000,0.000,0.5,0.5,0.0100,0.0007,0.800792,0.0788,0.55,0.45,0.451,0.426,0.200,0.200,0.56,0.400
22,0.333,0.333,0.333,0.000,0.0,0.0,0.0780,0.0213,1.509223,0.1580,0.55,0.65,0.720,0.724,0.573,0.540,0.56,0.667
23,0.333,0.333,0.000,0.333,0.0,0.0,0.0643,0.0161,1.347686,0.1380,0.60,0.50,0.665,0.649,0.488,0.454,0.68,0.467
24,0.333,0.000,0.333,0.333,0.0,0.0,0.0683,0.0202,1.674320,0.1771,0.55,0.40,0.681,0.708,0.660,0.622,0.56,0.333

**Get Excel sheet information with Python**

In [17]:
data1 = pandas.read_excel('multiple_sheets.xlsx')

data1

,ID,Large B/P,Large ROE,Large S/P,Large Return Rate in the last quarter,Large Market Value,Small systematic Risk,Annual Return,Excess Return,Systematic Risk,Total Risk,Abs. Win Rate,Rel. Win Rate,Annual Return.1,Excess Return.1,Systematic Risk.1,Total Risk.1,Abs. Win Rate.1,Rel. Win Rate.1
0,1,1.0,0.0,0.0,0.0,0,0,0.0195,0.0134,1.902608,0.2186,0.60,0.40,0.488,0.609,0.781,0.800,0.68,0.333
1,2,0.0,1.0,0.0,0.0,0,0,0.0238,0.0064,1.263287,0.1287,0.55,0.65,0.505,0.508,0.444,0.414,0.56,0.667
2,3,0.0,0.0,1.0,0.0,0,0,0.0803,0.0265,1.894339,0.2083,0.55,0.50,0.728,0.800,0.776,0.756,0.56,0.467
3,4,0.0,0.0,0.0,1.0,0,0,-0.0067,0.0007,1.425454,0.1555,0.55,0.35,0.385,0.426,0.529,0.529,0.56,0.267
4,5,0.0,0.0,0.0,0.0,1,0,0.0220,0.0044,1.094579,0.1067,0.65,0.70,0.498,0.479,0.355,0.320,0.80,0.733
5,6,0.0,0.0,0.0,0.0,0,1,-0.0534,-0.0149,0.859995,0.0889,0.40,0.30,0.200,0.200,0.231,0.243,0.20,0.200
6,7,0.5,0.5,0.0,0.0,0,0,0.0619,0.0163,1.392192,0.1441,0.55,0.65,0.656,0.652,0.512,0.480,0.56,0.667
7,8,0.5,0.0,0.5,0.0,0,0,0.0617,0.0234,1.939118,0.2182,0.60,0.50,0.655,0.754,0.800,0.798,0.68,0.467
8,9,0.0,0.5,0.5,0.0,0,0,0.0782,0.0197,1.354462,0.1377,0.55,0.70,0.720,0.700,0.492,0.453,0.56,0.733
9,10,0.5,0.0,0.0,0.5,0,0,0.0685,0.0190,1.524957,0.1628,0.55,0.40,0.682,0.691,0.582,0.561,0.56,0.333
10,11,0.0,0.5,0.0,0.5,0,0,0.0473,0.0123,1.247376,0.1318,0.65,0.65,0.598,0.594,0.435,0.427,0.80,0.667
11,12,0.0,0.0,0.5,0.5,0,0,0.0984,0.0264,1.591409,0.1661,0.60,0.55,0.800,0.797,0.617,0.575,0.68,0.533

**First 5 entries**
*this is built in default function*

In [18]:
data1.head()

,ID,Large B/P,Large ROE,Large S/P,Large Return Rate in the last quarter,Large Market Value,Small systematic Risk,Annual Return,Excess Return,Systematic Risk,Total Risk,Abs. Win Rate,Rel. Win Rate,Annual Return.1,Excess Return.1,Systematic Risk.1,Total Risk.1,Abs. Win Rate.1,Rel. Win Rate.1
0,1,1.0,0.0,0.0,0.0,0,0,0.0195,0.0134,1.902608,0.2186,0.60,0.40,0.488,0.609,0.781,0.800,0.68,0.333
1,2,0.0,1.0,0.0,0.0,0,0,0.0238,0.0064,1.263287,0.1287,0.55,0.65,0.505,0.508,0.444,0.414,0.56,0.667
2,3,0.0,0.0,1.0,0.0,0,0,0.0803,0.0265,1.894339,0.2083,0.55,0.50,0.728,0.800,0.776,0.756,0.56,0.467
3,4,0.0,0.0,0.0,1.0,0,0,-0.0067,0.0007,1.425454,0.1555,0.55,0.35,0.385,0.426,0.529,0.529,0.56,0.267
4,5,0.0,0.0,0.0,0.0,1,0,0.0220,0.0044,1.094579,0.1067,0.65,0.70,0.498,0.479,0.355,0.320,0.80,0.733

**First 10 entries**
*specify number*

In [19]:
data1.head(10)

,ID,Large B/P,Large ROE,Large S/P,Large Return Rate in the last quarter,Large Market Value,Small systematic Risk,Annual Return,Excess Return,Systematic Risk,Total Risk,Abs. Win Rate,Rel. Win Rate,Annual Return.1,Excess Return.1,Systematic Risk.1,Total Risk.1,Abs. Win Rate.1,Rel. Win Rate.1
0,1,1.0,0.0,0.0,0.0,0,0,0.0195,0.0134,1.902608,0.2186,0.60,0.40,0.488,0.609,0.781,0.800,0.68,0.333
1,2,0.0,1.0,0.0,0.0,0,0,0.0238,0.0064,1.263287,0.1287,0.55,0.65,0.505,0.508,0.444,0.414,0.56,0.667
2,3,0.0,0.0,1.0,0.0,0,0,0.0803,0.0265,1.894339,0.2083,0.55,0.50,0.728,0.800,0.776,0.756,0.56,0.467
3,4,0.0,0.0,0.0,1.0,0,0,-0.0067,0.0007,1.425454,0.1555,0.55,0.35,0.385,0.426,0.529,0.529,0.56,0.267
4,5,0.0,0.0,0.0,0.0,1,0,0.0220,0.0044,1.094579,0.1067,0.65,0.70,0.498,0.479,0.355,0.320,0.80,0.733
5,6,0.0,0.0,0.0,0.0,0,1,-0.0534,-0.0149,0.859995,0.0889,0.40,0.30,0.200,0.200,0.231,0.243,0.20,0.200
6,7,0.5,0.5,0.0,0.0,0,0,0.0619,0.0163,1.392192,0.1441,0.55,0.65,0.656,0.652,0.512,0.480,0.56,0.667
7,8,0.5,0.0,0.5,0.0,0,0,0.0617,0.0234,1.939118,0.2182,0.60,0.50,0.655,0.754,0.800,0.798,0.68,0.467
8,9,0.0,0.5,0.5,0.0,0,0,0.0782,0.0197,1.354462,0.1377,0.55,0.70,0.720,0.700,0.492,0.453,0.56,0.733
9,10,0.5,0.0,0.0,0.5,0,0,0.0685,0.0190,1.524957,0.1628,0.55,0.40,0.682,0.691,0.582,0.561,0.56,0.333

**Last 5 entries **

In [20]:
data1.tail()

,ID,Large B/P,Large ROE,Large S/P,Large Return Rate in the last quarter,Large Market Value,Small systematic Risk,Annual Return,Excess Return,Systematic Risk,Total Risk,Abs. Win Rate,Rel. Win Rate,Annual Return.1,Excess Return.1,Systematic Risk.1,Total Risk.1,Abs. Win Rate.1,Rel. Win Rate.1
7,8,0.5,0.0,0.5,0.0,0,0,0.0617,0.0234,1.939118,0.2182,0.60,0.50,0.655,0.754,0.800,0.798,0.68,0.467
8,9,0.0,0.5,0.5,0.0,0,0,0.0782,0.0197,1.354462,0.1377,0.55,0.70,0.720,0.700,0.492,0.453,0.56,0.733
9,10,0.5,0.0,0.0,0.5,0,0,0.0685,0.0190,1.524957,0.1628,0.55,0.40,0.682,0.691,0.582,0.561,0.56,0.333
10,11,0.0,0.5,0.0,0.5,0,0,0.0473,0.0123,1.247376,0.1318,0.65,0.65,0.598,0.594,0.435,0.427,0.80,0.667
11,12,0.0,0.0,0.5,0.5,0,0,0.0984,0.0264,1.591409,0.1661,0.60,0.55,0.800,0.797,0.617,0.575,0.68,0.533

**Last 10 Numbers**

In [21]:
data1.tail(10)

,ID,Large B/P,Large ROE,Large S/P,Large Return Rate in the last quarter,Large Market Value,Small systematic Risk,Annual Return,Excess Return,Systematic Risk,Total Risk,Abs. Win Rate,Rel. Win Rate,Annual Return.1,Excess Return.1,Systematic Risk.1,Total Risk.1,Abs. Win Rate.1,Rel. Win Rate.1
2,3,0.0,0.0,1.0,0.0,0,0,0.0803,0.0265,1.894339,0.2083,0.55,0.50,0.728,0.800,0.776,0.756,0.56,0.467
3,4,0.0,0.0,0.0,1.0,0,0,-0.0067,0.0007,1.425454,0.1555,0.55,0.35,0.385,0.426,0.529,0.529,0.56,0.267
4,5,0.0,0.0,0.0,0.0,1,0,0.0220,0.0044,1.094579,0.1067,0.65,0.70,0.498,0.479,0.355,0.320,0.80,0.733
5,6,0.0,0.0,0.0,0.0,0,1,-0.0534,-0.0149,0.859995,0.0889,0.40,0.30,0.200,0.200,0.231,0.243,0.20,0.200
6,7,0.5,0.5,0.0,0.0,0,0,0.0619,0.0163,1.392192,0.1441,0.55,0.65,0.656,0.652,0.512,0.480,0.56,0.667
7,8,0.5,0.0,0.5,0.0,0,0,0.0617,0.0234,1.939118,0.2182,0.60,0.50,0.655,0.754,0.800,0.798,0.68,0.467
8,9,0.0,0.5,0.5,0.0,0,0,0.0782,0.0197,1.354462,0.1377,0.55,0.70,0.720,0.700,0.492,0.453,0.56,0.733
9,10,0.5,0.0,0.0,0.5,0,0,0.0685,0.0190,1.524957,0.1628,0.55,0.40,0.682,0.691,0.582,0.561,0.56,0.333
10,11,0.0,0.5,0.0,0.5,0,0,0.0473,0.0123,1.247376,0.1318,0.65,0.65,0.598,0.594,0.435,0.427,0.80,0.667
11,12,0.0,0.0,0.5,0.5,0,0,0.0984,0.0264,1.591409,0.1661,0.60,0.55,0.800,0.797,0.617,0.575,0.68,0.533

**Summary of Dataframe** built in to the panda Dataframe type

In [22]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 19 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   ID                                     12 non-null     int64
 1   Large B/P                              12 non-null     float64
 2   Large ROE                              12 non-null     float64
 3   Large S/P                              12 non-null     float64
 4   Large Return Rate in the last quarter  12 non-null     float64
 5   Large Market Value                     12 non-null     int64
 6   Small systematic Risk                  12 non-null     int64
 7   Annual Return                          12 non-null     float64
 8   Excess Return                          12 non-null     float64
 9   Systematic Risk                        12 non-null     float64
 10  Total Risk                             12 non-null     float64
 11  Abs. Win Rate                          12 non-null     float64
 12  Rel. Win Rate                          12 non-null     float64
 13  Annual Return.1                        12 non-null     float64
 14  Excess Return.1                        12 non-null     float64
 15  Systematic Risk.1                      12 non-null     float64
 16  Total Risk.1                           12 non-null     float64
 17  Abs. Win Rate.1                        12 non-null     float64
 18  Rel. Win Rate.1                        12 non-null     float64
dtypes: float64(16), int64(3)
memory usage: 1.9 KB

**Dimension of the data type**  X is always listed First the Y is always listed Second. X being horizontally (rows) and Y vertically (columns)

In [24]:
data1.shape

(12, 19)

**Total rows**

In [25]:
rows = data1.shape[0]

rows

12

**Total columns**

In [26]:
columns = data1.shape[1]

columns

19

**Data type present in the dataframe**

In [27]:
data1.dtypes

ID                                         int64
Large B/P                                float64
Large ROE                                float64
Large S/P                                float64
Large Return Rate in the last quarter    float64
Large Market Value                         int64
Small systematic Risk                      int64
Annual Return                            float64
Excess Return                            float64
Systematic Risk                          float64
Total Risk                               float64
Abs. Win Rate                            float64
Rel. Win Rate                            float64
Annual Return.1                          float64
Excess Return.1                          float64
Systematic Risk.1                        float64
Total Risk.1                             float64
Abs. Win Rate.1                          float64
Rel. Win Rate.1                          float64
dtype: object

**Names of all columns**

In [28]:
data1.columns

Index(['ID', 'Large B/P', 'Large ROE', 'Large S/P',
       'Large Return Rate in the last quarter', 'Large Market Value',
       'Small systematic Risk', 'Annual Return', 'Excess Return',
       'Systematic Risk', 'Total Risk', 'Abs. Win Rate', 'Rel. Win Rate',
       'Annual Return.1', 'Excess Return.1', 'Systematic Risk.1',
       'Total Risk.1', 'Abs. Win Rate.1', 'Rel. Win Rate.1'],
      dtype='object')

**list a specfic column**

In [29]:
data1['ID']

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
Name: ID, dtype: int64

In [30]:
data1['Excess Return.1']

0     0.609
1     0.508
2     0.800
3     0.426
4     0.479
5     0.200
6     0.652
7     0.754
8     0.700
9     0.691
10    0.594
11    0.797
Name: Excess Return.1, dtype: float64